- name: "HackerU: Red Team Specialist"
  date: "Course: 2022.04 - 2022.12 | 565h"
  description: |
    - Linux & Windows
    - OS Exploitation
    - Privilege Escalation
    - Active Directory
    - Web & Mobile app Penetration testing
    - SIEM/SOC
    - Malware Analysis
- name: Self-learning Computer Science
  date: 2018 - Can it ever really end?
