name: Build HTML

on:
  workflow_dispatch:
  release:
    types: [push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir output

      - name: Build Markdown
        run: python scripts/generate.py --html

      - uses: docker://pandoc/minimal:edge
        with:
          args: >-
            output/before.md
            output/sidebar.md
            -o output/before.html
            --template templates/subsections.html
            --metadata-file meta/main.yaml

      - name: Build HTML
        uses: docker://pandoc/minimal:edge
        with:
          args: >-
            output/main.md
            -B output/before.html
            --standalone
            --template templates/main.html
            --metadata-file meta/main.yaml
            --output output/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output
